# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        docker:
            - image: circleci/node:11.10.0

        working_directory: ~/repo

        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v2-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v2-dependencies-

            - run: npm install

            - save_cache:
                  paths:
                      - node_modules
                  key: v2-dependencies-{{ checksum "package.json" }}

            # Restore the dist cache (for incremental builds)
            - restore_cache:
                  keys:
                      - dist-v2-{{ .Branch }}

            # run tests!
            - run: npm test

            # Save the dist cache (for incremental builds)
            - save_cache:
                  paths:
                      - dist
                  key: dist-v2-{{ .Branch }}-{{ epoch }}
